# Generated by Django 5.2.4 on 2025-09-18 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ceo', models.CharField(max_length=100)),
                ('est_year', models.PositiveIntegerField()),
                ('origin', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('seat_Capacity', models.CharField(max_length=100)),
                ('fuel_type', models.CharField(max_length=100)),
                ('cc', models.PositiveIntegerField()),
                ('mileage', models.PositiveIntegerField()),
                ('product_img', models.ImageField(blank=True, null=True, upload_to='products')),
                ('price', models.PositiveIntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='carsapp.company')),
            ],
        ),
    ]
