# Generated by Django 5.2.4 on 2025-09-21 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductExteriorImgs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exterior', models.ImageField(blank=True, null=True, upload_to='exterior')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exterior_images', to='carsapp.products')),
            ],
        ),
        migrations.CreateModel(
            name='ProductInteriorImgs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interior', models.ImageField(blank=True, null=True, upload_to='interior')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interior_images', to='carsapp.products')),
            ],
        ),
    ]
