# Generated by Django 5.2.4 on 2025-09-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=100)),
                ('Company', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('fuel_type', models.CharField(choices=[('petrol', 'PETROL'), ('diesel', 'DIESEL'), ('ev', 'EV')], max_length=100)),
                ('seat_capacity', models.CharField(choices=[('5 seater', '5 seater'), ('7 seater', '7 seater')], max_length=100)),
                ('transmission_type', models.CharField(choices=[('manual', 'MANUAL'), ('automated', 'AUTOMATED')], max_length=100)),
                ('total_km_driven', models.IntegerField()),
                ('amminities', models.CharField(max_length=100)),
                ('bootspace', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('car_img', models.ImageField(blank=True, null=True, upload_to='carimag')),
            ],
        ),
    ]
