# Generated by Django 5.2.4 on 2025-09-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='milage',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
